const traitNames = [
    "Backstabber",
    "Backswing A",
    "Backswing B",
    "Deadly d4",
    "Deadly d6",
    "Deadly d8",
    "Deadly d10",
    "Deadly d12",
    "Fatal d4",
    "Fatal d6",
    "Fatal d8",
    "Fatal d10",
    "Fatal d12",
    "Forceful 1",
    "Forceful 2",
    "Jousting 1",
    "Propulsive",
    "Twin 1",
];

const runeNames = [
    "Ghost Touch",
    "Disrupting",
    "Disrupting (Greater)",
    "Fearsome",
    "Fearsome (Greater)",
    "Wounding",
    "Corrosive",
    "Corrosive (Greater)",
    "Flaming",
    "Flaming (Greater)",
    "Frost",
    "Frost (Greater)",
    "Shock",
    "Shock (Greater)",
    "Thundering",
    "Thundering (Greater)",
    "Grevious",
    "Serrating",
    "Anarchic",
    "Axiomatic",
    "Holy",
    "Unholy",
    "Keen",
    "Vorpal",
    ];

export { traitNames, runeNames }