const runeNames = [
    "Ghost Touch",
    "Disrupting",
    "Disrupting (Greater)",
    "Fearsome",
    "Fearsome (Greater)",
    "Wounding",
    "Corrosive",
    "Corrosive (Greater)",
    "Flaming",
    "Flaming (Greater)",
    "Frost",
    "Frost (Greater)",
    "Shock",
    "Shock (Greater)",
    "Thundering",
    "Thundering (Greater)",
    "Grevious",
    "Serrating",
    "Anarchic",
    "Axiomatic",
    "Holy",
    "Unholy",
    "Keen",
    "Vorpal",
    ];

export { runeNames }